name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - run: cd server
      - name: Run Server Tests
        run: npm install
      - run: npm test

      - run: cd ../client
      - name: Run Client Tests
        run: npm install
      - run: npm test
